// Better Auth schema tables
// These tables are managed by Better Auth's Drizzle adapter

// Placeholder export to make this a valid module
// The actual schema will be generated by Better Auth when needed
export {};
